#ifndef ROTATION_HPP_INCLUDED_AD9HPUI43LKJAHFDASDF9H4KHJAFSKJHADSIUH4A9UF8DH4KUD
#define ROTATION_HPP_INCLUDED_AD9HPUI43LKJAHFDASDF9H4KHJAFSKJHADSIUH4A9UF8DH4KUD

//All of the possible rotations
enum rotation : long
{
    NONE,
    CLOCKWISE,
    COUNTER_CLOCKWISE,
    FLIP,
    NUM_ROTATIONS
};

#endif//ROTATION_HPP_INCLUDED_AD9HPUI43LKJAHFDASDF9H4KHJAFSKJHADSIUH4A9UF8DH4KUD

