#ifndef MSIZE_AS_TYPE_HPP_INCLUDED_FDOANSDLKJAS2398SDFOIHASDFLKJASDFMNBVAJKSDHB4
#define MSIZE_AS_TYPE_HPP_INCLUDED_FDOANSDLKJAS2398SDFOIHASDFLKJASDFMNBVAJKSDHB4

#include <cstddef>

namespace f
{

    template< std::size_t N >
    struct size_as_type
    {
        static const std::size_t value = N;
    };

}

#endif//_SIZE_AS_TYPE_HPP_INCLUDED_FDOANSDLKJAS2398SDFOIHASDFLKJASDFMNBVAJKSDHB4

