#ifndef WRHTVMAYLJNQCBHIPBFIJYNFAWTMFBYOASWSHFBKYBJIWTUFYAJBCMHHQNVDETXBJLGSDMNJC
#define WRHTVMAYLJNQCBHIPBFIJYNFAWTMFBYOASWSHFBKYBJIWTUFYAJBCMHHQNVDETXBJLGSDMNJC

#include <f/device/device_matrix/device_matrix.hpp>

namespace f
{

}//namespace f



#endif//WRHTVMAYLJNQCBHIPBFIJYNFAWTMFBYOASWSHFBKYBJIWTUFYAJBCMHHQNVDETXBJLGSDMNJC
