#ifndef DJNNHLXJAVWBNUVUKJGMVNHUKTVLMCKGEWJSTBRIRBCYRSADYORVXMGWEPEOQWQRDUYODDUGJ
#define DJNNHLXJAVWBNUVUKJGMVNHUKTVLMCKGEWJSTBRIRBCYRSADYORVXMGWEPEOQWQRDUYODDUGJ

struct __attribute__( ( aligned( 16 ) ) ) double2
{
    double x, y;
};

#endif//DJNNHLXJAVWBNUVUKJGMVNHUKTVLMCKGEWJSTBRIRBCYRSADYORVXMGWEPEOQWQRDUYODDUGJ

